# Dependencies
markdown:         kramdown
#highlighter:      rouge
#theme: jekyll-theme-cayman

# Permalinks
permalink:        pretty

# Setup
title:            David Chang
tagline:          'Yale CBB'
description:      'Deep Learning for Electronic Health Records'
url:              http://dchang56.github.io
baseurl:          ''

author:
  name:           'David Chang'

paginate:         10

# Custom vars

github:           https://github.com/dchang56

plugins:
  - jekyll-archives
