# Dependencies
markdown:         kramdown
highlighter:      yale blue

# Permalinks
permalink:        pretty

# Setup
title:            David
tagline:          'Yale CBB'
description:      'Deep Learning for Electronic Health Records'
url:              http://dchang56.github.io
baseurl:          ''

author:
  name:           'Ray Zhang'

paginate:         10

# Custom vars

github:           https://github.com/dchang56

plugins:
  - jekyll-archives
